# Generated by Django 4.0 on 2021-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardrooms',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
