# Generated by Django 4.0 on 2021-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_boardrooms_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardrooms',
            name='name',
            field=models.CharField(error_messages={'unique': 'The name you entered already exist'}, max_length=255, unique=True),
        ),
    ]
