# Generated by Django 4.0 on 2021-12-19 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_boardrooms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardrooms',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Use positive number only')]),
        ),
    ]
