# Generated by Django 4.0 on 2021-12-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_boardrooms_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardrooms',
            name='name',
            field=models.CharField(error_messages={'unique': 'This name already exist'}, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rese_date', models.DateField()),
                ('comment', models.TextField()),
                ('boardrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.boardrooms')),
            ],
            options={
                'unique_together': {('rese_date', 'boardrooms')},
            },
        ),
    ]
