# Generated by Django 4.0 on 2022-01-04 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_boardrooms_name_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='rese_date',
            field=models.DateField(default=datetime.date(2022, 1, 4)),
        ),
    ]
