# Generated by Django 4.0 on 2022-01-15 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_reservations_rese_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='rese_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 15, 14, 31, 22, 934894, tzinfo=utc), validators=[home.validators.date_validator]),
        ),
    ]
