# Generated by Django 4.0 on 2022-01-16 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_reservations_rese_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='boardrooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardrooms', to='home.boardrooms'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='rese_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 12, 55, 26, 474824, tzinfo=utc), validators=[home.validators.date_validator], verbose_name='Reservation date'),
        ),
    ]
