# Generated by Django 4.0 on 2022-01-16 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_reservations_boardrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='boardrooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.boardrooms'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='rese_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 12, 57, 40, 204757, tzinfo=utc), validators=[home.validators.date_validator], verbose_name='Reservation date'),
        ),
    ]
