# Generated by Django 4.0 on 2022-01-16 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_reservations_boardrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='rese_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 13, 0, 16, 187740, tzinfo=utc), validators=[home.validators.date_validator], verbose_name='Reservation date'),
        ),
    ]
