# Generated by Django 4.0 on 2022-01-16 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_reservations_rese_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='rese_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 16, 0, 40, 232676, tzinfo=utc), validators=[home.validators.date_validator], verbose_name='Reservation date'),
        ),
    ]
